////////////////////////////////////////////////////////////////////////////////
//	created:	2004/12/22
//	file base:	VS_UI_PCH.h
// 
////////////////////////////////////////////////////////////////////////////////

#pragma once

#pragma warning(disable:4290)
#pragma warning(disable:4018)
#pragma warning(disable:4244)


#pragma warning(push)
#pragma warning(disable:4018)
#pragma warning(disable:4786)

#include <string>
#include <vector>
#include <map>
#include <list>
#include <deque>
#include <bitset>
#include <algorithm>
#include <iostream.h>
#include <fstream.h>
#include <windows.h>
#include <assert.h>
#include <time.h>

#pragma warning(pop)

using std::string;
using std::vector;
using std::map;
using std::list;
using std::deque;
using std::bitset;


