/*-----------------------------------------------------------------------------

	VS_UI_GlobalResource.h

	특정 Object의 자원이 아닌 것들.

	2000.8.9. KJTINC

-----------------------------------------------------------------------------*/

#ifndef __VS_UI_GLOBALRESOURCE_H__
#define __VS_UI_GLOBALRESOURCE_H__

#include "VS_UI_Base.h"
#include "VS_UI_Util.h"

//-----------------------------------------------------------------------------
// C_GLOBAL_RESOURCE
//
//
//-----------------------------------------------------------------------------
class C_GLOBAL_RESOURCE
{
public:
	//
	// 외부에서 직접 접근한다.
	//
	//C_ANI_OBJECT *				m_pC_ao_ani_button;
//	Tga *							m_pic_box_back; // 조립박스 배경
//	C_SPRITE_PACK *			m_pC_box_line_spk;
//	C_SPRITE_PACK *			m_pC_ok_spk;

//	enum COMMON_BUTTON_INDEX
//	{
//		SMALL_BUTTON,
//		SMALL_FOCUS_BUTTON,
//		SMALL_PUSHED_BUTTON,
//		GO_BUTTON,
//		GO_FOCUS_BUTTON,
//		GO_PUSHED_BUTTON,
//		BACK_BUTTON,
//		BACK_FOCUS_BUTTON,
//		BACK_PUSHED_BUTTON,
//		NEXT_BUTTON_OFFSET = 9, // 3x3
//	};

//	C_SPRITE_PACK *			m_pC_common_button; // toggle용 작은버튼, OK, Cancel ...

	//
	//	(1) (2) (3)
	// (4) (5) (6)
	// (7) (8) (9)
	//
	enum ASSEMBLE_BOX_INDEX
	{
//		AB_LEFTUP,		// (1)
//		AB_UP,			// (2)
//		AB_RIGHTUP,		// (3)
//		AB_LEFT,			// (4)
//		AB_CENTER,		// (5)
//		AB_RIGHT,		// (6)
//		AB_LEFTDOWN,	// (7)
//		AB_DOWN,			// (8)
//		AB_RIGHTDOWN,	// (9)
		AB_BACK,
		AB_BACK_ALPHA,
		AB_RIGHT,
		AB_DOWN,
		AB_RIGHTDOWN,
		AB_BACK2,
		AB_BACK_ALPHA2,
		AB_RIGHT2,
		AB_DOWN2,
		AB_RIGHTDOWN2,

		// 여기부턴 아우스터즈만 있음
		AB_DOWN4,
		AB_RIGHTDOWN4,
	};

	C_SPRITE_PACK *			m_pC_assemble_box_spk;

	enum ASSEMBLE_BOX_BUTTON_INDEX
	{
		AB_BUTTON_OK,
		AB_BUTTON_OK_HILIGHTED,
		AB_BUTTON_OK_PUSHED,
		AB_BUTTON_CANCEL,
		AB_BUTTON_CANCEL_HILIGHTED,
		AB_BUTTON_CANCEL_PUSHED,
		AB_BUTTON_CLOSE,
		AB_BUTTON_CLOSE_HILIGHTED,
		AB_BUTTON_CLOSE_PUSHED,
		AB_BUTTON_HELP,
		AB_BUTTON_HELP_HILIGHTED,
		AB_BUTTON_HELP_PUSHED,
		AB_BUTTON_O,
		AB_BUTTON_O_HILIGHTED,
		AB_BUTTON_O_PUSHED,
		AB_BUTTON_QUESTION,
		AB_BUTTON_QUESTION_HILIGHTED,
		AB_BUTTON_QUESTION_PUSHED,
		AB_BUTTON_DESC,
		AB_BUTTON_DESC_HILIGHTED,
		AB_BUTTON_DESC_PUSHED,
		AB_BUTTON_MONEY,
		AB_BUTTON_MONEY_HILIGHTED,
		AB_BUTTON_MONEY_PUSHED,
		AB_BUTTON_X,
		AB_BUTTON_X_HILIGHTED,
		AB_BUTTON_X_PUSHED,
		AB_BUTTON_CHANGE_MONEY,
		AB_BUTTON_CHANGE_MONEY_HILIGHTED,
		AB_BUTTON_CHANGE_MONEY_PUSHED,
		
		AB_DIALOG_TAG,
		AB_DIALOG_TAG_SELECTED,

		AB_NAME_BAR,
		AB_MONEY_BAR,

		AB_BUTTON_PUSHPIN,
		AB_BUTTON_PUSHPIN_PUSHED,

		AB_BUTTON_ALPHA,
		AB_BUTTON_ALPHA_PUSHED,

		AB_BUTTON_JOINING,
		AB_BUTTON_JOINING_HILIGHTED,
		AB_BUTTON_JOINING_PUSHED,
		AB_BUTTON_ABSENCE,
		AB_BUTTON_ABSENCE_HILIGHTED,
		AB_BUTTON_ABSENCE_PUSHED,
		
		AB_BUTTON_SELECT,
		AB_BUTTON_SELECT_HILIGHTED,
		AB_BUTTON_SELECT_PUSHED,

		AB_BUTTON_CHANGE,
		AB_BUTTON_CHANGE_HILIGHTED,
		AB_BUTTON_CHANGE_PUSHED,

		AB_TITLE_DECORATION_LEFT,
		AB_TITLE_DECORATION_RIGHT,

		//add by viva
		AB_BUTTON_FRIEND_BLACK,
		AB_BUTTON_FRIEND_BLACK_HILIGHTED,
		AB_BUTTON_FRIEND_BLACK_PUSHED,
		//end

		AB_BUTTON_HILIGHTED_OFFSET = 1,
		AB_BUTTON_PUSHED_OFFSET = 2,
	};

	C_SPRITE_PACK *			m_pC_assemble_box_button_spk;

//	enum ASSEMBLE_BOX_ETC
//	{
//		AB_SCROLL_UP,
//		AB_SCROLL_DOWN,
//		AB_SCROLL_UP_PUSHED,
//		AB_SCROLL_DOWN_PUSHED,
//		AB_SCROLL_TAG,
//		AB_LEFT_ARROW,
//		AB_RIGHT_ARROW,
//	};
//
//	C_SPRITE_PACK *			m_pC_assemble_box_etc_spk;

	enum SCROLL_BAR
	{
		SB_BAR,
		SB_BUTTON,
		SB_BUTTON_PUSHED,
		SB_BUTTON_HILIGHTED,
		SB_BUTTON_HILIGHTED_PUSHED,
		SB_TAG,
		SB_BAR_WIDTH,
		SB_TAG_WIDTH,
	};

	enum SCROLL_BAR3
	{
		SB3_BAR,
		SB3_BUTTON_UP,
		SB3_BUTTON_UP_HILIGHTED,
		SB3_BUTTON_UP_PUSHED,
		SB3_BUTTON_DOWN,
		SB3_BUTTON_DOWN_HILIGHTED,
		SB3_BUTTON_DOWN_PUSHED,
		SB3_TAG,
	};

	C_SPRITE_PACK *			m_pC_scroll_bar_spk;

	enum BOX
	{
		OB_MAIN,
		OB_RIGHT,
		OB_DOWN,
		OB_RIGHTDOWN,

		IB_MAIN,
		IB_RIGHT,
		IB_DOWN,
		IB_RIGHTDOWN,
	};

	enum INFO_SPK
	{
		//common
		TAB_CHAR,
		TAB_SKILL,
		TAB_GRADE1,
		TAB_GRADE2,
		TAB_GRADE3,
		BUTTON_CLOSE_BACK,
		BUTTON_CLOSE,
		BUTTON_CLOSE_PUSHED,
		BUTTON_CLOSE_HILIGHTED,
		BUTTON_CLOSE_HILIGHTED_PUSHED,
		BUTTON_HELP_BACK,
		BUTTON_HELP,
		BUTTON_HELP_PUSHED,
		BUTTON_HELP_HILIGHTED,
		BUTTON_HELP_HILIGHTED_PUSHED,
		CHAR_BOX,
		DESC_BOX,
		LARGE_BAR,
		LARGE_BAR_RIGHT,
		SMALL_BAR,
		SMALL_BAR2,
		EXP_BAR,
		GUILD_BACK,
		SKILL_TITLE,
		SKILL_ICON_BACK,
		SKILL_BACK,
		SKILL_BACK_HILIGHTED,
		SKILL_BACK_ALPHA,
		SKILL_BOX,
		TITLE_NAME,
		TITLE_ALIGN,
		TITLE_GUILD,
		TITLE_STR,
		TITLE_DEX,
		TITLE_INT,
		TITLE_HP,
		TITLE_TOHIT,
		TITLE_DAMAGE,
		TITLE_DEFENCE,
		TITLE_PROTECTION,
		GRADE_LEVEL,
		GRADE_LEVEL_HILIGHTED,
		GRADE_EXP,
		GRADE_EXP_HILIGHTED,		
		GRADE_RED_BUTTON,
		GRADE_RED_BUTTON_DISABLE,

		//slayer
		TITLE_FAME,
		TITLE_MP,
		TITLE_DOMAINLEVEL,
		TITLE_DOMAINEXP,
		PLUS_BUTTON,
		PLUS_BUTTON_HILIGHTED,
		PLUS_BUTTON_HILIGHTED_PUSHED,
		MINUS_BUTTON,
		MINUS_BUTTON_HILIGHTED,
		MINUS_BUTTON_HILIGHTED_PUSHED,
		SUM_BUTTON,
		SUM_BUTTON_HILIGHTED,
		SUM_BUTTON_HILIGHTED_PUSHED,
		DOMAIN_BACK,
		DOMAIN_BAR,
		DM_BLADE,
		DM_BLADE_HILIGHTED,
		DM_SWORD,
		DM_SWORD_HILIGHTED,
		DM_GUN,
		DM_GUN_HILIGHTED,
		DM_HEAL,
		DM_HEAL_HILIGHTED,
		DM_ENCHANT,
		DM_ENCHANT_HILIGHTED,
		DM_TOTAL,
		DM_TOTAL_HILIGHTED,
		TITLE_GRADE,
		TITLE_TEAM,
		GRADE_PIVATE,
		GRADE_PIVATE_HILIGHTED,
		GRADE_SERENT,
		GRADE_SERENT_HILIGHTED,
		GRADE_FEACEL,								
		GRADE_FEACEL_HILIGHTED,
		GRADE_LITENA,
		GRADE_LITENA_HILIGHTED,
		GRADE_KAINEL,
		GRADE_KAINEL_HILIGHTED,
		SLAYER_GRADE_BAR,
		SLAYER_GRADE_BAR_HILIGHTED,
		SLAYER_GRADE_BAR_PUSHED,
		SLAYER_GRADE_BAR_HILIGHTED_PUSHED,
		SLAYER_GRADE_MARK_EDGE,
		SLAYER_CHANGE_IMAGE,
		SLAYER_CHANGE_IMAGE_HILIGHTED,
		SLAYER_CHANGE_IMAGE_PUSHED,
		GRADE_GENEAL,
		GRADE_GENEAL_HILIGHTED,
		GRADE_FORE_GENEAL,
		GRADE_FORE_GENEAL_HILIGHTED,
		GRADE_MAJORIS_GENEAL,								
		GRADE_MAJORIS_GENEAL_HILIGHTED,
		GRADE_CLOEL_GENEAL,
		GRADE_CLOEL_GENEAL_HILIGHTED,
		GRADE_MARSHAL,
		GRADE_MARSHAL_HILIGHTED,
		ADVANCEMENT_SLAYERS_SKILL,
		ADVANCEMENT_SLAYERS_SKILLQUAD,
		ADVANCEMENT_SLAYERS_SKILLQUAD_BAR,
		ADVANCEMENT_CHINGHO,
		ADVANCEMENT_CHINGHO_NAME,
		ADVANCEMENT_CHINGHO_EXP,
		ADVANCEMENT_CHINGHO_KIND,
		ADVANCEMENT_CHINGHO_SKILL,
		ADVANCEMENT_BONUS_POINT,
//		ADVANCEMENT_CHINGHO_TITLE,
//		ADVANCEMENT_CHINGHO_NUM1,
//		ADVANCEMENT_CHINGHO_NUM2,
//		ADVANCEMENT_CHINGHO_NUM3,
//		ADVANCEMENT_CHINGHO_NUM4,
//		ADVANCEMENT_CHINGHO_NUM5,
//		ADVANCEMENT_CHINGHO_NUM6,
//		ADVANCEMENT_CHINGHO_NUM7,
//		ADVANCEMENT_CHINGHO_NUM8,
//		ADVANCEMENT_CHINGHO_NUM9,
//		ADVANCEMENT_CHINGHO_NUM10,
//		ADVANCEMENT_CHINGHO_NUM_1,
//		ADVANCEMENT_CHINGHO_NUM_2,
//		ADVANCEMENT_CHINGHO_NUM_3,
//		ADVANCEMENT_CHINGHO_NUM_4,
//		ADVANCEMENT_CHINGHO_NUM_5,
//		ADVANCEMENT_CHINGHO_NUM_6,
//		ADVANCEMENT_CHINGHO_NUM_7,
//		ADVANCEMENT_CHINGHO_NUM_8,
//		ADVANCEMENT_CHINGHO_NUM_9,
//		ADVANCEMENT_CHINGHO_NUM_10,

		//VAMPIRE
		TITLE_LEVEL = TITLE_FAME,
		TITLE_BONUS,
		TITLE_EXP,
		BONUS_BUTTON,
		BONUS_BUTTON_HILIGHTED,
		BONUS_BUTTON_HILIGHTED_PUSHED,
		DM_POISON,
		DM_POISON_HILIGHTED,
		DM_ACID,
		DM_ACID_HILIGHTED,
		DM_CURSE,
		DM_CURSE_HILIGHTED,
		DM_SUMMON,
		DM_SUMMON_HILIGHTED,
		DM_BLOOD,
		DM_BLOOD_HILIGHTED,
		DM_INNATE,
		DM_INNATE_HILIGHTED,
		TITLE_GRADE2,
		TITLE_CLAN,
		GRADE_RITTER,
		GRADE_RITTER_HILIGHTED,
		GRADE_REICHSRITTER,
		GRADE_REICHSRITTER_HILIGHTED,
		GRADE_BARONET,	
		GRADE_BARONET_HILIGHTED,
		GRADE_PREYHER,
		GRADE_PREYHER_HILIGHTED,
		GRADE_GRAF,
		GRADE_GRAF_HILIGHTED,
		VAMPIRE_GRADE_BAR,
		VAMPIRE_GRADE_BAR_HILIGHTED,
		VAMPIRE_GRADE_BAR_PUSHED,
		VAMPIRE_GRADE_BAR_HILIGHTED_PUSHED,
		GRADE_BAR_BACK,
		GRADE_BAR,
		VAMPIRE_GRADE_MARK_EDGE,
		VAMPIRE_FAME,
		VAMPIRE_CHANGE_IMAGE,
		VAMPIRE_CHANGE_IMAGE_HILIGHTED,
		VAMPIRE_CHANGE_IMAGE_PUSHED,
		GRADE_MARKGRAF,
		GRADE_MARKGRAF_HILIGHTED,
		GRADE_PFALZGRAF,
		GRADE_PFALZGRAF_HILIGHTED,
		GRADE_FURST,								
		GRADE_FURST_HILIGHTED,
		GRADE_HERZOG,
		GRADE_HERZOG_HILIGHTED,
		GRADE_LANDESHER,
		GRADE_LANDESHER_HILIGHTED,
		ADVANCEMENT_VAMPIRE_SKILL,
		ADVANCEMENT_VAMPIRE_SKILLQUAD,
		ADVANCEMENT_VAMPIRE_SKILLQUAD_BAR,
		ADVANCEMENT_VAMPIRE_CHINGHO,
		ADVANCEMENT_VAMPIRE_CHINGHO_NAME,
		ADVANCEMENT_VAMPIRE_CHINGHO_EXP,
		ADVANCEMENT_VAMPIRE_CHINGHO_KIND,
		ADVANCEMENT_VAMPIRE_CHINGHO_SKILL,
//		ADVANCEMENT_VAMPIRE_CHINGHO_TITLE,
//		ADVANCEMENT_VAMPIRE_CHINGHO_NUM1,
//		ADVANCEMENT_VAMPIRE_CHINGHO_NUM2,
//		ADVANCEMENT_VAMPIRE_CHINGHO_NUM3,
//		ADVANCEMENT_VAMPIRE_CHINGHO_NUM4,
//		ADVANCEMENT_VAMPIRE_CHINGHO_NUM5,
//		ADVANCEMENT_VAMPIRE_CHINGHO_NUM6,
//		ADVANCEMENT_VAMPIRE_CHINGHO_NUM7,
//		ADVANCEMENT_VAMPIRE_CHINGHO_NUM8,
//		ADVANCEMENT_VAMPIRE_CHINGHO_NUM9,
//		ADVANCEMENT_VAMPIRE_CHINGHO_NUM10,
//		ADVANCEMENT_VAMPIRE_CHINGHO_NUM_1,
//		ADVANCEMENT_VAMPIRE_CHINGHO_NUM_2,
//		ADVANCEMENT_VAMPIRE_CHINGHO_NUM_3,
//		ADVANCEMENT_VAMPIRE_CHINGHO_NUM_4,
//		ADVANCEMENT_VAMPIRE_CHINGHO_NUM_5,
//		ADVANCEMENT_VAMPIRE_CHINGHO_NUM_6,
//		ADVANCEMENT_VAMPIRE_CHINGHO_NUM_7,
//		ADVANCEMENT_VAMPIRE_CHINGHO_NUM_8,
//		ADVANCEMENT_VAMPIRE_CHINGHO_NUM_9,
//		ADVANCEMENT_VAMPIRE_CHINGHO_NUM_10,



		//ousters
//		OUSTERS_TITLE_LEVEL = TITLE_FAME,
//		OUSTERS_TITLE_BONUS,
//		OUSTERS_TITLE_EXP,
//		OUSTERS_BONUS_BUTTON,
//		OUSTERS_BONUS_BUTTON_HILIGHTED,
//		OUSTERS_BONUS_BUTTON_HILIGHTED_PUSHED,
		OUSTERS_DM_COMBAT = DM_POISON,
		OUSTERS_DM_COMBAT_HILIGHTED,
		OUSTERS_DM_ELEMENTAL,
		OUSTERS_DM_ELEMENTAL_HILIGHTED,
		OUSTERS_TITLE_GRADE2,
		OUSTERS_TITLE_GUILD,		
//		OUSTERS_GRADE_MALCHUT,
//		OUSTERS_GRADE_MALCHUT_HILIGHTED,
		OUSTERS_GRADE_YESOD,	
		OUSTERS_GRADE_YESOD_HILIGHTED,
		OUSTERS_GRADE_HOD,
		OUSTERS_GRADE_HOD_HILIGHTED,
		OUSTERS_GRADE_NETRETH,
		OUSTERS_GRADE_NETRETH_HILIGHTED,
		OUSTERS_GRADE_TIPHRETH,
		OUSTERS_GRADE_TIPHRETH_HILIGHTED,
		OUSTERS_GRADE_BAR,
		OUSTERS_GRADE_BAR_HILIGHTED,
		OUSTERS_GRADE_BAR_PUSHED,
		OUSTERS_GRADE_BAR_HILIGHTED_PUSHED,
		OUSTERS_GRADE_BAR2_BACK,
		OUSTERS_GRADE_BAR2,
		OUSTERS_GRADE_MARK_EDGE,
		OUSTERS_FAME,
		OUSTERS_SKILL_LEVEL,
		OUSTERS_SKILL_POINT,
		OUSTERS_EP,
		OUSTERS_SKILL_BACK,
		OUSTERS_LEARN_BUTTON,
		OUSTERS_LEARN_BUTTON_HILIGHTED,
		OUSTERS_LEARN_BUTTON_PUSHED,
		OUSTERS_PLUS_BUTTON,
		OUSTERS_PLUS_BUTTON_HILIGHTED,
		OUSTERS_PLUS_BUTTON_PUSHED,
		OUSTERS_ELEMENTAL_MARK_FIRE,
		OUSTERS_ELEMENTAL_MARK_WATER,
		OUSTERS_ELEMENTAL_MARK_EARTH,
		OUSTERS_HORN,
		OUSTERS_HORN_HILIGHTED,
		OUSTERS_DOWN_SKILL_BUTTON,
		OUSTERS_DOWN_SKILL_BUTTON_HILIGHTED,
		OUSTERS_DOWN_SKILL_BUTTON_PUSHED,
		OUSTERS_CHANGE_IMAGE,
		OUSTERS_CHANGE_IMAGE_HILIGHTED,
		OUSTERS_CHANGE_IMAGE_PUSHED,
		GRADE_GEBURAH,
		GRADE_GEBURAH_HILIGHTED,
		GRADE_CHESED,
		GRADE_CHESED_HILIGHTED,
		GRADE_BINSH,								
		GRADE_BINSH_HILIGHTED,
		GRADE_CHOKMA,
		GRADE_CHOKMA_HILIGHTED,
		GRADE_KEATHER,
		GRADE_KEATHER_HILIGHTED,
		OUSTERS_SKILL_BACK_2,
		ADVANCEMENT_OUSTERS_SKILL,
		ADVANCEMENT_OUSTERS_SKILLQUAD,
		ADVANCEMENT_OUSTERS_SKILLQUAD_BAR,
		ADVANCEMENT_OUSTERS_CHINGHO,
		ADVANCEMENT_OUSTERS_CHINGHO_NAME,
		ADVANCEMENT_OUSTERS_CHINGHO_EXP,
		ADVANCEMENT_OUSTERS_CHINGHO_KIND,
		ADVANCEMENT_OUSTERS_CHINGHO_SKILL,
//		ADVANCEMENT_OUSTERS_CHINGHO_TITLE,
//		ADVANCEMENT_OUSTERS_CHINGHO_NUM1,
//		ADVANCEMENT_OUSTERS_CHINGHO_NUM2,
//		ADVANCEMENT_OUSTERS_CHINGHO_NUM3,
//		ADVANCEMENT_OUSTERS_CHINGHO_NUM4,
//		ADVANCEMENT_OUSTERS_CHINGHO_NUM5,
//		ADVANCEMENT_OUSTERS_CHINGHO_NUM6,
//		ADVANCEMENT_OUSTERS_CHINGHO_NUM7,
//		ADVANCEMENT_OUSTERS_CHINGHO_NUM8,
//		ADVANCEMENT_OUSTERS_CHINGHO_NUM9,
//		ADVANCEMENT_OUSTERS_CHINGHO_NUM10,
//		ADVANCEMENT_OUSTERS_CHINGHO_NUM_1,
//		ADVANCEMENT_OUSTERS_CHINGHO_NUM_2,
//		ADVANCEMENT_OUSTERS_CHINGHO_NUM_3,
//		ADVANCEMENT_OUSTERS_CHINGHO_NUM_4,
//		ADVANCEMENT_OUSTERS_CHINGHO_NUM_5,
//		ADVANCEMENT_OUSTERS_CHINGHO_NUM_6,
//		ADVANCEMENT_OUSTERS_CHINGHO_NUM_7,
//		ADVANCEMENT_OUSTERS_CHINGHO_NUM_8,
//		ADVANCEMENT_OUSTERS_CHINGHO_NUM_9,
//		ADVANCEMENT_OUSTERS_CHINGHO_NUM_10,
	};


	C_SPRITE_PACK	*m_pC_box_spk;
	C_SPRITE_PACK	* m_pC_info_spk;

	C_GLOBAL_RESOURCE();
	~C_GLOBAL_RESOURCE();

	void	LoadAssemble();
	void	FreeAssemble();

	// OutBox?
	void	DrawOutBox(int x, int y, int w, int h);
	void	DrawOutBox(Rect &rect);
	void	DrawOutBoxLocked(int x, int y, int w, int h);
	void	DrawOutBoxLocked(Rect &rect);

	// InBox?
	void	DrawInBox(int x, int y, int w, int h);
	void	DrawInBox(Rect &rect);
	void	DrawInBoxLocked(int x, int y, int w, int h);
	void	DrawInBoxLocked(Rect &rect);
	
	// Dialog
	void	DrawDialog(int x, int y, int w, int h, bool alpha = false);
	void	DrawDialog(Rect &rect, bool alpha = false);
	void	DrawDialogLocked(int x, int y, int w, int h, bool alpha = false);
	void	DrawDialogLocked(Rect &rect, bool alpha = false);
	void	DrawDialog2(int x, int y, int w, int h, bool alpha = false);
	void	DrawDialog2(Rect &rect, bool alpha = false);
	void	DrawDialogLocked2(int x, int y, int w, int h, bool alpha = false);
	void	DrawDialogLocked2(Rect &rect, bool alpha = false);
	
	// 아우스터즈 배경 바꾼거
	void	DrawDialog4(int x, int y, int w, int h, bool alpha = false);
	void	DrawDialog4(Rect &rect, bool alpha = false);
	void	DrawDialogLocked4(int x, int y, int w, int h, bool alpha = false);
	void	DrawDialogLocked4(Rect &rect, bool alpha = false);
	// 알파는 빼고 테두리만
	void	DrawDialogOnly(int x, int y, int w, int h);
	void	DrawDialogOnly(Rect &rect);
	void	DrawDialogOnlyLocked(int x, int y, int w, int h);
	void	DrawDialogOnlyLocked(Rect &rect);
	void	DrawDialogOnly2(int x, int y, int w, int h);
	void	DrawDialogOnly2(Rect &rect);
	void	DrawDialogOnlyLocked2(int x, int y, int w, int h);
	void	DrawDialogOnlyLocked2(Rect &rect);	
	
	void	DrawTempChatBoxLocked(int x, int y, int w, int h, bool alpha = false);
};

extern C_GLOBAL_RESOURCE *	gpC_global_resource;
extern bool	gbl_wood_skin;

#endif