#ifndef __VS_UI_UIMESSAGE_H__
#define __VS_UI_UIMESSAGE_H__

// message
enum UI_MESSAGE
{
	INVALID_MESSAGE,

	UI_STORAGE_BUY,
	UI_SELECT_STORAGE_SLOT,
	UI_RUNNING_GAMEMENU,
	UI_FINISH_LEVELUP_BUTTON,
	UI_CLICK_BONUS_POINT,
	UI_INFO,

//	UI_MINIMAP_TOGGLE,
	UI_DROP_MONEY,
	UI_EXCHANGE_REQUEST_CANCEL,
	UI_EXCHANGE_ACCEPT,
	UI_EXCHANGE_MONEY,
	UI_WITHDRAW_MONEY,
	UI_ITEM_SELECT_EXCHANGE,	
	UI_DEPOSIT_MONEY,
	UI_CHECK_EXIST_ID,
	UI_RUN_NEWUSER_REGISTRATION,
	UI_INFO_CLOSE,
	UI_GAMEMENU_CONTINUE,
/*
	//
	// PDS
	//
	UI_CHANGE_PCS_CONNECTED_SLOT,
	UI_PLEASE_PCS_CONNECT_ME,
	UI_PCS_CONNECTOR_GRANTED,
	UI_QUIT_PCS_ONLINE_MODE,
	UI_END_PCS,
	UI_SEND_PCS_NUMBER,
	UI_PDS_CLOSED,

	UI_PLEASE_SET_SLAYER_VALUE,
*/
//	UI_CLOSE_SKILL_TREE,
//	UI_CLOSE_SKILL_VIEW,

	UI_BACKGROUND_MOUSE_FOCUS,
	UI_REMOVE_BACKGROUND_MOUSE_FOCUS,

	//
	//
	UI_BUY_ITEM,

	UI_SELL_ITEM,
	UI_REPAIR_ITEM,
	UI_SILVERING_ITEM,
	UI_ITEM_SELL_FINISHED,
	UI_ITEM_REPAIR_FINISHED,
	UI_ITEM_SILVERING_FINISHED,

	UI_CLOSE_SHOP,
	UI_CLOSE_STORAGE,
	UI_CLOSE_EXCHANGE,
	UI_CANCEL_EXCHANGE,
	UI_OK_EXCHANGE,

	UI_CHARACTER_MANAGER_FINISHED,
	UI_TERMINATION,
	UI_LOGIN,
	UI_LOGOUT,								
	UI_CONNECT,							   // Game connection.
	UI_CHAT_RETURN,
	UI_SELECT_SKILL,						// Skill selection.
	UI_CANCEL_SELECT_SKILL,

	//
	// Item message
	//

	// drop
	UI_ITEM_DROP_TO_CLIENT,
	UI_ITEM_DROP_TO_INVENTORY,
	UI_ITEM_DROP_TO_GEAR,
	UI_ITEM_DROP_TO_QUICKSLOT,

	// pick up
	//UI_ITEM_PICKUP_FROM_TRADEGRID,
	UI_ITEM_PICKUP_FROM_INVENTORY,
	UI_ITEM_PICKUP_FROM_GEAR,
	UI_ITEM_PICKUP_FROM_QUICKSLOT,

	// insert to other Item
	//UI_ITEM_INSERT_FROM_TRADEGRID,
	UI_ITEM_INSERT_FROM_INVENTORY,
	UI_ITEM_INSERT_FROM_GEAR,
	UI_ITEM_INSERT_FROM_QUICKSLOT,

	// use
	UI_ITEM_USE,
	UI_ITEM_USE_QUICKSLOT,

	//
	// Character management
	//
	UI_NEW_CHARACTER,
	UI_DELETE_CHARACTER,

	// etc
	UI_CLOSE_BBS,

	// game option
	UI_CHANGE_OPTION,
	UI_CLOSE_OPTION,

	// title option
//	UI_CHANGE_TITLE_OPTION,
//	UI_CLOSE_TITLE_OPTION,	

	// repleace	

	//tutorial by larosel
	UI_CLOSE_BOOKCASE,
	UI_CLOSE_BRIEFING,
	UI_CLOSE_COMPUTER,
	UI_CLOSE_TUTORIAL_EXIT,

	UI_CLOSE_DESC_DIALOG,
	UI_CLOSE_ELEVATOR,
	UI_SELECT_ELEVATOR,

	UI_SELL_ALL_ITEM,
	

	UI_ITEM_TO_QUICKITEMSLOT, // focus_grid_x, focus_grid_y, (MItem *)p_item

	UI_CLOSE_SLAYER_PORTAL,
	UI_SLAYER_PORTAL,

	UI_FINISH_REQUEST_PARTY_BUTTON,
	UI_PARTY_REQUEST_CANCEL, 
	UI_PARTY_ACCEPT,

	UI_CLOSE_PARTY_MANAGER,
	UI_AWAY_PARTY,

	UI_FINISH_REQUEST_DIE_BUTTON,

	UI_CLOSE_TEAM_LIST,
	UI_CLOSE_TEAM_INFO,
	UI_CLOSE_TEAM_MEMBER_INFO,
	UI_CLOSE_TEAM_REGIST,
	UI_CLOSE_TEAM_MEMBER_LIST,
	
	UI_REQUEST_GUILD_INFO,
	UI_REQUEST_GUILD_MEMBER_LIST,
	UI_MODIFY_GUILD_MEMBER,

	UI_SELECT_TEAM_MEMBER_LIST,			// void_ptr = CHAR_NAME
	UI_SELECT_READY_TEAM_LIST,		// void_ptr = TEAM_NAME
	UI_SELECT_REGIST_TEAM_LIST,		// void_ptr = TEAM_NAME
//add by viva
	UI_CLOSE_FRIEND_CHATTING_INFO,
	UI_OPEN_FRIEND_CHATTING_INFO,
	///////friend message
	UI_FRIEND_CHATTING_SEND_MESSAGE,
	UI_FRIEND_CHATTING_UPDATE,
	UI_FRIEND_CHATTING_ADD_FRIEND,
	///////ask_friend_request
	UI_FRIEND_REQUEST_ACCEPT,
	UI_FRIEND_ASK_CLOSE,
	////////ask_friend_delete
	UI_FRIEND_DELETE_ASK,
	UI_FRIEND_DELETE_ACCEPT,
//end
	UI_JOIN_READY_TEAM,				// void_ptr = TEAM_NAME
	UI_JOIN_REGIST_TEAM,			// void_ptr = TEAM_NAME

	UI_REGIST_GUILD_MEMBER,
	UI_REGIST_GUILD_TEAM,

	UI_CLOSE_FILE_DIALOG,			// left = mode, void_ptr = file_name

	UI_CONNECT_SERVER,				// left == true : group false : server right : id
	UI_CLOSE_SERVER_SELECT,			// left == true : group false : server

	UI_NEWCHARACTER_CHECK,				// void_ptr : name

	UI_ENCHANT_ACCEPT,
	UI_ENCHANT_CANCEL,
	
	UI_MESSAGE_BOX,

	//UI_OTHER_INFO,					// Other Player Info Box
	UI_CLOSE_OTHER_INFO,			//            //
	UI_MODIFY_TEAM_INFO,
	UI_MODIFY_GUILD_MEMBER_INTRO,

	UI_CLOSE_TRACE_WINDOW,
	UI_SEND_NAME_FOR_SOUL_CHAIN,

	UI_RUN_CONNECT,
	UI_SELECT_GRADE_SKILL,

	UI_USE_XMAS_TREE,				// left = ItemPointer, void_ptr = message
	UI_CLOSE_XMAS_CARD_WINDOW,
	UI_SEND_BRING_FEE,				// left = money				to client
	UI_CLOSE_BRING_FEE_WINDOW,		// close window

	UI_CLOSE_WAR_LIST_WINDOW,

	UI_CLOSE_BLOOD_BIBLE_STATUS,

	UI_SEND_NAME_FOR_COUPLE,
	UI_CLOSE_INPUT_NAME,
	
	UI_ITEM_USE_GEAR,
	UI_GO_BILING_PAGE,

	UI_CLOSE_POPUP_MESSAGE,
	UI_CLOSE_QUEST_STATUS,
	UI_CLOSE_LOTTERY_CARD,
	UI_LOTTERY_CARD_STATUS,				// left = step, right = GiftID
	UI_FINISH_SCRATCH_LOTTERY,
	
	UI_CLOSE_IMAGE_NOTICE,
	
	UI_SELECT_ITEM_FROM_SHOP,
	UI_CLOSE_ITEM_LIST,
	UI_CLOSE_BULLETIN_BOARD_WINDOW,
	
	UI_TRANS_ITEM_CANCEL,
	UI_TRANS_ITEM_ACCEPT,

	UI_FINISH_REQUEST_RESURRECT_BUTTON,

	UI_USE_MIXING_FORGE,
	UI_CLOSE_MIXING_FORGE,

	UI_CLOSE_REMOVE_OPTION,
	UI_SEND_REMOVE_OPTION,

	UI_CLOSE_OUSTERS_SKILL_INFO,
	UI_OUSTERS_LEARN_SKILL,
	
	UI_RUN_LEVELUP,
	
	UI_CLOSE_HORN,
	UI_OUSTERS_DOWN_SKILL,
	
	UI_CLOSE_FINDING_MINE,
	UI_CLOSE_NEMONEMO,
	UI_CLOSE_PUSHPUSH,
	UI_CLOSE_CRAZY_MINE,
	UI_CLOSE_ARROW_TILE,
	UI_CLEAR_STAGE,					// left = (minigame|stage) right = time
	UI_CLEAR_ALL_STAGE,
	UI_REQUEST_FORCE_DIE,
	UI_ADD_ITEM_TO_CODE_SHEET,		// left = x , right = y, ptr = item
	
	UI_SEND_BUG_REPORT,				// left = line, ptr = string
	UI_GO_TO_BEGINNER_ZONE,

	UI_POPUP_MESSAGE_OK,			// left = ID, right = selectedID
	UI_CLOSE_SHRINE_MINIMAP,		// left ?
	UI_WARP_REGEN_TOWER,			// left id num;

	UI_CLOSE_MAILBOX,
	
	UI_CLOSE_PET_INFO,
	UI_PET_GAMBLE,
	UI_CLOSE_USE_PET_FOOD,
	
	UI_CLOSE_PETSTORAGE,
	UI_CLOSE_KEEP_PETITEM,
	UI_CLOSE_GET_KEEP_PETITEM,
	UI_KEEP_PETITEM,
	UI_GET_KEEP_PETITEM,
	// 2004, 5, 11 sobeit add end

	UI_CLOSE_SMS_MESSAGE,
	UI_SEND_SMS_MESSAGE,
	UI_SMS_OPEN_LIST,
	UI_SMS_RECORD,
	UI_SMS_DELETE,
	UI_CLOSE_SMS_LIST,
	UI_CLOSE_SMS_RECORD,
	UI_SMS_ADD_SEND_LIST,

	UI_CLOSE_NAMING,
	UI_CHANGE_CUSTOM_NAMING,
	UI_SELECT_NAMING,
	UI_CLOSE_NAMING_CHANGE,
	UI_RUN_NAMING_CHANGE,
	// 2004, 6, 15 sobeit add end
	
	// 2004, 7, 5, sobeit add start
	UI_CLOSE_QUEST_MANAGER,
	UI_CLOSE_QUEST_LIST,
	UI_CLOSE_QUEST_DETAIL,
	UI_CLOSE_QUEST_MISSION,
	UI_CLOSE_QUEST_ITEM,
	UI_CLOSE_QUEST_ICON,
	UI_GQUEST_ACCEPT,
	UI_GQUEST_GIVEUP,
	
	// 2004, 7, 5, sobeit add end

	UI_ITEM_USE_GQUEST_ITEM,

	UI_REQUEST_UNION,
	UI_REQUEST_UNION_ACCEPT,
	UI_REQUEST_UNION_DENY,
	UI_REQUEST_UNION_REQUEST_DENY,
	UI_REQUEST_UNION_REQUEST_INFO,
	UI_REQUEST_UNION_EXPERGUILD,
	UI_REQUEST_UNION_QUIT,
	UI_REQUEST_UNION_QUIT_ACCEPT,
	UI_REQUEST_UNION_QUIT_DENY,

	UI_REQUEST_UNION_REQUEST_GUILD_LIST,

	UI_RECALL_BY_NAME,
	
	UI_MODIFY_TAX,
	UI_APPOINT_SUBMASTER,
	
	UI_CLOSE_PERSNALSHOP,
	UI_SELECT_PERSNALSHOP_SLOT,
	UI_CLOSE_PERSNALSHOP_MESSAGE,
	UI_INPUT_PERSNALSHOP_MESSAGE,
	
	UI_DISPLAY_ITEM,
    UI_UNDISPLAY_ITEM,
    UI_STORE_SIGN,
    UI_STORE_OPEN,
    UI_STORE_CLOSE,
	UI_REQUEST_STORE_INFO,
	UI_MY_STORE_INFO,
    UI_OTHER_STORE_INFO,
	
    UI_BUY_STORE_ITEM,
    UI_REMOVE_STORE_ITEM,
    UI_ADD_STORE_ITEM,

	// 2004, 11, 30, sobeit add start
	UI_CLOSE_POWER_JJANG,
	UI_REQUEST_POWER_JJANG_POINT,
	UI_POWER_JJANG_GAMBLE,
	// 2004, 11, 30, sobeit add end
	
	UI_CLOSE_SWAPADVANCEMENTITEM,
	UI_SWAPADVANCEMENTITEM,
	UI_LEARN_ADVANCE_SKILL,

	UI_CAMPAIGN_HELP,

	UI_RUN_NEXT_GQUEST_EXCUTE_ELEMENT,
	
	UI_GQUEST_SET_ACTION,
	UI_GQUEST_ENDING_EVENT,
	
	UI_REQUEST_EVENT_ITEM,

	UI_CLOSE_INVENTORY_SUB,
	UI_ITEM_DROP_TO_INVENTORY_SUB,
	UI_ITEM_PICKUP_FROM_INVENTORY_SUB,

	UI_ITEM_USE_SUBINVENTORY,
	MAX_UI_MESSAGE
};

#endif