//----------------------------------------------------------------------
// MEffectGeneratorDef.h
//----------------------------------------------------------------------

#ifndef __MEFFECTGENERATORDEF_H__
#define __MEFFECTGENERATORDEF_H__

//----------------------------------------------------------------------
// class ID
//----------------------------------------------------------------------
enum ENUM_EFFECTGENERATORID 
{
	EFFECTGENERATORID_ATTACK_CREATURE = 0,
	EFFECTGENERATORID_ATTACK_ZONE,
	EFFECTGENERATORID_ATTACK_ZONE_PARABOLA,
	EFFECTGENERATORID_STOP_ZONE,
	EFFECTGENERATORID_RISING,
	EFFECTGENERATORID_FALLING,
	EFFECTGENERATORID_ATTACK_CREATURE_PARABOLA,
	EFFECTGENERATORID_ATTACH_CREATURE,
	EFFECTGENERATORID_ATTACH_CREATURE_GROUND,
	EFFECTGENERATORID_STOP_ZONE_CROSS,
	EFFECTGENERATORID_STOP_ZONE_X,
	EFFECTGENERATORID_STOP_ZONE_RECT,
	EFFECTGENERATORID_STOP_ZONE_RHOMBUS,
	EFFECTGENERATORID_RIPPLE_ZONE,
	EFFECTGENERATORID_RIPPLE_ZONE_WIDE,
	EFFECTGENERATORID_STOP_INVENTORY,
	EFFECTGENERATORID_STOP_ZONE_MULTIPLE,
	EFFECTGENERATORID_MULTIPLE_FALLING,
	EFFECTGENERATORID_STOP_ZONE_RANDOM,
	EFFECTGENERATORID_ATTACH_ZONE,
	EFFECTGENERATORID_STOP_ZONE_WALL,	
	EFFECTGENERATORID_RIPPLE_ZONE_PIXEL,	
	EFFECTGENERATORID_STOP_ZONE_SELECTABLE,	
	EFFECTGENERATORID_ATTACH_ZONE_SELECTABLE,	
	EFFECTGENERATORID_SPREAD_OUT,
	EFFECTGENERATORID_BLOODY_WALL,
	EFFECTGENERATORID_ATTACK_CREATURE_HOMING,
	EFFECTGENERATORID_BLOODY_WAVE,
	EFFECTGENERATORID_AROUND_ZONE,
	EFFECTGENERATORID_STOP_ZONE_EMPTY_CROSS,			// 2002.3.23.. cross에서 가운데것이 빠진것
	EFFECTGENERATORID_STOP_ZONE_EMPTY_RECT,				// 가운데 빠진 것. 사각형
	EFFECTGENERATORID_STOP_ZONE_EMPTY_HORIZONTAL_WALL,	// 가운데 빠진 것. 가로로
	EFFECTGENERATORID_STOP_ZONE_EMPTY_VERTICAL_WALL,	// 가운데 빠진 것. 세로로
	EFFECTGENERATORID_ATTACK_ZONE_BOMB,					// 폭탄 던지기
	EFFECTGENERATORID_ATTACH_CREATURE_ORBIT,			// 캐릭터에 붙는 위성? 이펙트.. 빙빙 돈다.
	EFFECTGENERATORID_METEOR_DROP,						// 메테오 전용
	EFFECTGENERATORID_BLOODY_BREAKER,					// 2003.2.26 블러디 브레이커
	EFFECTGENERATORID_ATTACH_ZONE_AROUND,				// 해당 지점의 주변이 터진다.
	EFFECTGENERATORID_ATTACK_ZONE_RECT,
	EFFECTGENERATORID_FOLLOW_PATH,						// 만들어진 길을 따라간다.
	EFFECTGENERATORID_FIRE_PIECING,
	EFFECTGENERATORID_SKIP_DRAW,
	EFFECTGENERATORID_PLAYING_WITH_FIRE,
	
	MAX_EFFECTGENERATORID	
};


#endif