//----------------------------------------------------------------------
// MusicDef.h
//----------------------------------------------------------------------

#ifndef __MUSICDEF_H__
#define __MUSICDEF_H__

enum MUSIC_ID
{
	MUSIC_TREASURE,
	MUSIC_WHISPER,
	MUSIC_SAY_AGAIN,
	MUSIC_WINDMILL,
	MUSIC_HELL_KNIGHT,
	MUSIC_HOLLOWEEN,
	MUSIC_PAY_BACK,
	MUSIC_HIDE_AWAY,
	MUSIC_LIVE_OR_DEAD,
	MUSIC_LUNATIC,
	MUSIC_MARCHING,

	// 2001.12.17 Ãß°¡
	MUSIC_XMAS_JINGLEBELL,
	MUSIC_XMAS_SILENTNIGHT,
	MUSIC_XMAS_SILVERBELL,

	MUSIC_HOLYLAND,
	MUSIC_HOLYLAND_WAR,
	MUSIC_OCTAVUS,
	MUSIC_SEPTIMUS,
	MUSIC_TERTIUS,
	MUSIC_QUARTUS,
	
	MUSIC_ILLUSIONS_WAY,
	MUSIC_GDR_LAIR,

	MAX_MUSIC
};

#endif