#ifndef	__RANKBONUSDEF_H__
#define	__RANKBONUSDEF_H__

	enum RankBonusType
	{
		RANK_BONUS_DEADLY_SPEAR,
		RANK_BONUS_BEHEMOTH_ARMOR,
		RANK_BONUS_DARGON_EYE,
		RANK_BONUS_IMMORTAL_HEART,
		RANK_BONUS_RELIANCE_BRAIN,
		RANK_BONUS_SLAYING_KNIFE,
		RANK_BONUS_HAWK_WING,
		RANK_BONUS_HOLY_SMASHING,
		RANK_BONUS_SOUL_SMASHING,
		RANK_BONUS_SAPPHIRE_BLESS,
		RANK_BONUS_RUBY_BLESS,
		RANK_BONUS_DIAMOND_BLESS,
		RANK_BONUS_EMERALD_BLESS,
		RANK_BONUS_MAGIC_BRAIN,
		RANK_BONUS_WIGHT_HAND,
		RANK_BONUS_SEIREN_HAND,
		RANK_BONUS_FORTUNE_HAND,

		RANK_BONUS_IMMORTAL_BLOOD,
		RANK_BONUS_BEHEMOTH_SKIN,
		RANK_BONUS_SAFE_ROBE,
		RANK_BONUS_CROW_WING,
		RANK_BONUS_WISDOM_OF_BLOOD,
		RANK_BONUS_TIGER_NAIL,
		RANK_BONUS_URANUS_BLESS,
		RANK_BONUS_DISRUPTION_STORM,
		RANK_BONUS_WIDE_STORM,
		RANK_BONUS_KNOWLEDGE_OF_POISON,
		RANK_BONUS_KNOWLEDGE_OF_ACID,
		RANK_BONUS_KNOWLEDGE_OF_CURSE,
		RANK_BONUS_KNOWLEDGE_OF_BLOOD,
		RANK_BONUS_KNOWLEDGE_OF_INNATE,
		RANK_BONUS_KNOWLEDGE_OF_SUMMON,
		RANK_BONUS_WISDOM_OF_SWAMP,
		RANK_BONUS_WISDOM_OF_SILENCE,
		RANK_BONUS_WISDOM_OF_DARKNESS,
		RANK_BONUS_WIDE_DARKNESS,

		RANK_BONUS_WOOD_SKIN,
        RANK_BONUS_WIND_SENSE,
        RANK_BONUS_HOMING_EYE,
        RANK_BONUS_LIFE_ENERGY,
        RANK_BONUS_SOUL_ENERGY,
        RANK_BONUS_STONE_MAUL,
        RANK_BONUS_SWIFT_ARM,
        RANK_BONUS_FIRE_ENDOW,
        RANK_BONUS_WATER_ENDOW,
        RANK_BONUS_EARTH_ENDOW,
        RANK_BONUS_ANTI_ACID_SKIN,
		RANK_BONUS_ANTI_BLOODY_SKIN,
        RANK_BONUS_ANTI_CURSE_SKIN,
        RANK_BONUS_ANTI_POISON_SKIN,
        RANK_BONUS_ANTI_SILVER_DAMAGE_SKIN,
        RANK_BONUS_BLESS_OF_NATURE,
        RANK_BONUS_LIFE_ABSORB,
        RANK_BONUS_SOUL_ABSORB,
        RANK_BONUS_MYSTIC_RULE,

		// 2Â÷ Ãß°¡
		RANK_BONUS_PERCEPTION,          // 55
        RANK_BONUS_STONE_OF_SAGE,           // 56
        RANK_BONUS_FOOT_OF_RANGER,          // 57
        RANK_BONUS_WARRIORS_FIST,           // 58

        RANK_BONUS_ACID_INQUIRY,            // 59
        RANK_BONUS_BLOODY_INQUIRY,          // 60
        RANK_BONUS_CURSE_INQUIRY,           // 61
        RANK_BONUS_POISON_INQUIRY,          // 62
		RANK_BONUS_INQUIRY_MASTERY,         // 63
   
        RANK_BONUS_POWER_OF_SPIRIT,         // 64
        RANK_BONUS_WIND_OF_SPIRIT,          // 65
        RANK_BONUS_PIXIES_EYES,         // 66
        RANK_BONUS_GROUND_OF_SPIRIT,            // 67
        RANK_BONUS_FIRE_OF_SPIRIT,          // 68

        RANK_BONUS_EVOLUTION_IMMORTAL_HEART,            // 69
        RANK_BONUS_BEHEMOTH_ARMOR_2,            // 70
        RANK_BONUS_DRAGON_EYE_2,            // 71
        RANK_BONUS_EVOLUTION_RELIANCE_BRAIN,            // 72
        RANK_BONUS_HEAT_CONTROL,            // 73

		RANK_BONUS_ACID_MASTERY,            // 74
        RANK_BONUS_BLOODY_MASTERY,          // 75
        RANK_BONUS_CURSE_MASTERY,           // 76
        RANK_BONUS_POISON_MASTERY,          // 77
        RANK_BONUS_SKILL_MASTERY,           // 78

        RANK_BONUS_SALAMANDERS_KNOWLEDGE,           // 79
        RANK_BONUS_UNDINES_KNOWLEDGE,           // 80
        RANK_BONUS_GNOMES_KNOWLEDGE,            // 81


		RANK_BONUS_MAX
	};

#endif