Update SkillBalance Set HName = 'Not Defined' where Type =0;
Update SkillBalance Set HName = 'Not Defined' where Type =1;
Update SkillBalance Set HName = 'Not Defined' where Type =2;
Update SkillBalance Set HName = 'Not Defined' where Type =3;
Update SkillBalance Set HName = 'Not Defined' where Type =4;
Update SkillBalance Set HName = '双重打击' where Type =5;
Update SkillBalance Set HName = '三倍打击' where Type =6;
Update SkillBalance Set HName = '彩虹攻击' where Type =7;
Update SkillBalance Set HName = '雷光闪电' where Type =8;
Update SkillBalance Set HName = '飞舞之剑' where Type =9;
Update SkillBalance Set HName = '反击' where Type =10;
Update SkillBalance Set HName = '闪电滑行' where Type =11;
Update SkillBalance Set HName = '电光铁手' where Type =12;
Update SkillBalance Set HName = '灵蛇闪动' where Type =13;
Update SkillBalance Set HName = '波浪之剑' where Type =14;
Update SkillBalance Set HName = 'Not Defined' where Type =15;
Update SkillBalance Set HName = 'Not Defined' where Type =16;
Update SkillBalance Set HName = 'Not Defined' where Type =17;
Update SkillBalance Set HName = '精准打击' where Type =18;
Update SkillBalance Set HName = '罗旋一击' where Type =19;
Update SkillBalance Set HName = '三倍爆击' where Type =20;
Update SkillBalance Set HName = '野蛮爆击' where Type =21;
Update SkillBalance Set HName = '幽灵之刃' where Type =22;
Update SkillBalance Set HName = '潜力爆炸' where Type =23;
Update SkillBalance Set HName = '尾行之术' where Type =24;
Update SkillBalance Set HName = '能量补充' where Type =25;
Update SkillBalance Set HName = '狂风骤击' where Type =26;
Update SkillBalance Set HName = '断空斩' where Type =27;
Update SkillBalance Set HName = 'Not Defined' where Type =28;
Update SkillBalance Set HName = 'Not Defined' where Type =29;
Update SkillBalance Set HName = 'Not Defined' where Type =30;
Update SkillBalance Set HName = '快速装填' where Type =31;
Update SkillBalance Set HName = '急速火焰' where Type =32;
Update SkillBalance Set HName = 'SMG熟练度' where Type =33;
Update SkillBalance Set HName = '散射' where Type =34;
Update SkillBalance Set HName = '爆头' where Type =35;
Update SkillBalance Set HName = 'AR熟练度' where Type =36;
Update SkillBalance Set HName = '烈焰指' where Type =37;
Update SkillBalance Set HName = '狙击' where Type =38;
Update SkillBalance Set HName = 'SG熟练度' where Type =39;
Update SkillBalance Set HName = '启示者' where Type =40;
Update SkillBalance Set HName = '炸弹制造' where Type =41;
Update SkillBalance Set HName = 'SR熟练度' where Type =42;
Update SkillBalance Set HName = 'Not Defined' where Type =43;
Update SkillBalance Set HName = '地雷安装' where Type =44;
Update SkillBalance Set HName = '地雷制造' where Type =45;
Update SkillBalance Set HName = '圣水制造' where Type =46;
Update SkillBalance Set HName = '照明术' where Type =47;
Update SkillBalance Set HName = '探测术' where Type =48;
Update SkillBalance Set HName = '圣光弹' where Type =49;
Update SkillBalance Set HName = '大地祝福' where Type =50;
Update SkillBalance Set HName = '高级照明术' where Type =51;
Update SkillBalance Set HName = '光耀之环' where Type =52;
Update SkillBalance Set HName = '净化术' where Type =53;
Update SkillBalance Set HName = '神圣光环' where Type =54;
Update SkillBalance Set HName = '突击' where Type =55;
Update SkillBalance Set HName = '侦测隐形' where Type =56;
Update SkillBalance Set HName = 'Not Defined' where Type =57;
Update SkillBalance Set HName = '圣光盾' where Type =58;
Update SkillBalance Set HName = 'Not Defined' where Type =59;
Update SkillBalance Set HName = '明目术' where Type =60;
Update SkillBalance Set HName = 'Not Defined' where Type =61;
Update SkillBalance Set HName = 'Not Defined' where Type =62;
Update SkillBalance Set HName = '治疗术' where Type =63;
Update SkillBalance Set HName = '解毒' where Type =64;
Update SkillBalance Set HName = '毒液抵抗' where Type =65;
Update SkillBalance Set HName = '光击术' where Type =66;
Update SkillBalance Set HName = '伤害治疗术' where Type =67;
Update SkillBalance Set HName = '解除诅咒' where Type =68;
Update SkillBalance Set HName = '诅咒抗力' where Type =69;
Update SkillBalance Set HName = '高级光击术' where Type =70;
Update SkillBalance Set HName = '高级治疗术' where Type =71;
Update SkillBalance Set HName = '酸性防护' where Type =72;
Update SkillBalance Set HName = '牺牲' where Type =73;
Update SkillBalance Set HName = '裁决之箭' where Type =74;
Update SkillBalance Set HName = '全体治疗' where Type =75;
Update SkillBalance Set HName = '光辉领域' where Type =76;
Update SkillBalance Set HName = 'Not Defined' where Type =77;
Update SkillBalance Set HName = 'Not Defined' where Type =78;
Update SkillBalance Set HName = '吸血' where Type =79;
Update SkillBalance Set HName = '剧毒之触' where Type =80;
Update SkillBalance Set HName = '荧绿之毒' where Type =81;
Update SkillBalance Set HName = '艳黄之毒' where Type =82;
Update SkillBalance Set HName = '幽暗之毒' where Type =83;
Update SkillBalance Set HName = '毒雾' where Type =84;
Update SkillBalance Set HName = '酸性之触' where Type =85;
Update SkillBalance Set HName = '酸矢' where Type =86;
Update SkillBalance Set HName = '酸球' where Type =87;
Update SkillBalance Set HName = '酸性沼泽' where Type =88;
Update SkillBalance Set HName = '麻痹' where Type =89;
Update SkillBalance Set HName = '毁灭' where Type =90;
Update SkillBalance Set HName = '迷幻术' where Type =91;
Update SkillBalance Set HName = '致死术' where Type =92;
Update SkillBalance Set HName = '血爪' where Type =93;
Update SkillBalance Set HName = '血刃' where Type =94;
Update SkillBalance Set HName = '血球' where Type =95;
Update SkillBalance Set HName = '血墙' where Type =96;
Update SkillBalance Set HName = '血矛' where Type =97;
Update SkillBalance Set HName = '隐蔽' where Type =98;
Update SkillBalance Set HName = '黑暗之触' where Type =99;
Update SkillBalance Set HName = '隐身' where Type =100;
Update SkillBalance Set HName = '变身-狼' where Type =101;
Update SkillBalance Set HName = '变身-蝙蝠' where Type =102;
Update SkillBalance Set HName = '召唤-狼' where Type =103;
Update SkillBalance Set HName = '召唤-棺材' where Type =104;
Update SkillBalance Set HName = '死亡装饰' where Type =105;
Update SkillBalance Set HName = '召唤-仆人' where Type =106;
Update SkillBalance Set HName = 'Not Defined' where Type =107;
Update SkillBalance Set HName = '攫飘罚胶汽' where Type =108;
Update SkillBalance Set HName = '攫牢厚瘤呼府萍' where Type =109;
Update SkillBalance Set HName = '己荐 带瘤扁' where Type =110;
Update SkillBalance Set HName = '吞噬尸体' where Type =111;
Update SkillBalance Set HName = '战争咆哮' where Type =112;
Update SkillBalance Set HName = 'Not Defined' where Type =113;
Update SkillBalance Set HName = '血之印记' where Type =114;
Update SkillBalance Set HName = '血之漩涡' where Type =115;
Update SkillBalance Set HName = '诱惑' where Type =116;
Update SkillBalance Set HName = '撕裂之风' where Type =117;
Update SkillBalance Set HName = '地震术' where Type =118;
Update SkillBalance Set HName = '复活' where Type =119;
Update SkillBalance Set HName = '祈祷' where Type =120;
Update SkillBalance Set HName = '冥想' where Type =121;
Update SkillBalance Set HName = '雷鸣剑' where Type =122;
Update SkillBalance Set HName = '体力增幅' where Type =123;
Update SkillBalance Set HName = 'Not Defined' where Type =124;
Update SkillBalance Set HName = 'Not Defined' where Type =125;
Update SkillBalance Set HName = 'Not Defined' where Type =126;
Update SkillBalance Set HName = '我最猛' where Type =127;
Update SkillBalance Set HName = '狂暴' where Type =128;
Update SkillBalance Set HName = '断月斩' where Type =129;
Update SkillBalance Set HName = '暗影舞者' where Type =130;
Update SkillBalance Set HName = '狂野台风' where Type =131;
Update SkillBalance Set HName = 'Not Defined' where Type =132;
Update SkillBalance Set HName = 'Not Defined' where Type =133;
Update SkillBalance Set HName = 'Not Defined' where Type =134;
Update SkillBalance Set HName = 'Not Defined' where Type =135;
Update SkillBalance Set HName = 'Not Defined' where Type =136;
Update SkillBalance Set HName = 'Not Defined' where Type =137;
Update SkillBalance Set HName = '天使之赐福' where Type =138;
Update SkillBalance Set HName = '明镜止水' where Type =139;
Update SkillBalance Set HName = '圣光风暴' where Type =140;
Update SkillBalance Set HName = 'Exorcism' where Type =141;
Update SkillBalance Set HName = '避难所' where Type =142;
Update SkillBalance Set HName = '反弹' where Type =143;
Update SkillBalance Set HName = '哈米吉多顿' where Type =144;
Update SkillBalance Set HName = '毒性攻击' where Type =145;
Update SkillBalance Set HName = '毒液风暴' where Type =146;
Update SkillBalance Set HName = '酸性攻击' where Type =147;
Update SkillBalance Set HName = '酸性风暴' where Type =148;
Update SkillBalance Set HName = '血腥攻击' where Type =149;
Update SkillBalance Set HName = '血腥风暴' where Type =150;
Update SkillBalance Set HName = 'Not Defined' where Type =151;
Update SkillBalance Set HName = 'Not Defined' where Type =152;
Update SkillBalance Set HName = 'Not Defined' where Type =153;
Update SkillBalance Set HName = '死亡契约' where Type =154;
Update SkillBalance Set HName = 'Not Defined' where Type =155;
Update SkillBalance Set HName = '血液互补' where Type =156;
Update SkillBalance Set HName = '黑暗复仇者' where Type =157;
Update SkillBalance Set HName = '血浪' where Type =158;
Update SkillBalance Set HName = '炸弹投掷' where Type =159;
Update SkillBalance Set HName = '二连射' where Type =160;
Update SkillBalance Set HName = '三连射' where Type =161;
Update SkillBalance Set HName = 'Not Defined' where Type =162;
Update SkillBalance Set HName = 'Not Defined' where Type =163;
Update SkillBalance Set HName = '大地爆击' where Type =164;
Update SkillBalance Set HName = '圣光雨' where Type =165;
Update SkillBalance Set HName = '剑法熟练度' where Type =166;
Update SkillBalance Set HName = '盾牌熟练度' where Type =167;
Update SkillBalance Set HName = '雷鸣风暴' where Type =168;
Update SkillBalance Set HName = '心神凝聚' where Type =169;
Update SkillBalance Set HName = '逃脱术' where Type =170;
Update SkillBalance Set HName = '神圣冲击' where Type =171;
Update SkillBalance Set HName = '神圣之歌' where Type =172;
Update SkillBalance Set HName = '凝心剑' where Type =173;
Update SkillBalance Set HName = '专注之眼' where Type =174;
Update SkillBalance Set HName = 'Not Defined' where Type =175;
Update SkillBalance Set HName = 'Not Defined' where Type =176;
Update SkillBalance Set HName = '开棺' where Type =177;
Update SkillBalance Set HName = '召唤-怪物' where Type =178;
Update SkillBalance Set HName = '大地之击' where Type =179;
Update SkillBalance Set HName = '陨石术' where Type =180;
Update SkillBalance Set HName = '分身术' where Type =181;
Update SkillBalance Set HName = '高级血浪术' where Type =182;
Update SkillBalance Set HName = '血腥扭曲' where Type =183;
Update SkillBalance Set HName = '嗜血灵蛇' where Type =184;
Update SkillBalance Set HName = '灵魂锁链' where Type =185;
Update SkillBalance Set HName = '灭绝' where Type =186;
Update SkillBalance Set HName = 'Not Defined' where Type =187;
Update SkillBalance Set HName = 'Not Defined' where Type =188;
Update SkillBalance Set HName = 'Not Defined' where Type =189;
Update SkillBalance Set HName = '尖刺之盾' where Type =190;
Update SkillBalance Set HName = '大闪电' where Type =191;
Update SkillBalance Set HName = '元气盾' where Type =192;
Update SkillBalance Set HName = '大地能量' where Type =193;
Update SkillBalance Set HName = '光之子弹' where Type =194;
Update SkillBalance Set HName = '炮火支援' where Type =195;
Update SkillBalance Set HName = '群体催眠' where Type =196;
Update SkillBalance Set HName = '精灵护卫' where Type =197;
Update SkillBalance Set HName = '不死转换' where Type =198;
Update SkillBalance Set HName = '智慧之触' where Type =199;
Update SkillBalance Set HName = '光球' where Type =200;
Update SkillBalance Set HName = '神圣箭矢' where Type =201;
Update SkillBalance Set HName = '血腥破坏' where Type =202;
Update SkillBalance Set HName = '快速滑行' where Type =203;
Update SkillBalance Set HName = '魔法回避' where Type =204;
Update SkillBalance Set HName = '毒网' where Type =205;
Update SkillBalance Set HName = '复仇幻想' where Type =206;
Update SkillBalance Set HName = '生命意志' where Type =207;
Update SkillBalance Set HName = '魔法免疫' where Type =208;
Update SkillBalance Set HName = '攻击反射' where Type =209;
Update SkillBalance Set HName = '神圣之盾' where Type =210;
Update SkillBalance Set HName = '剑气' where Type =211;
Update SkillBalance Set HName = '连续切割' where Type =212;
Update SkillBalance Set HName = '利爪熟练度' where Type =213;
Update SkillBalance Set HName = '攻击转换' where Type =214;
Update SkillBalance Set HName = '狂野台风' where Type =215;
Update SkillBalance Set HName = '终极突袭' where Type =216;
Update SkillBalance Set HName = '修罗-破' where Type =217;
Update SkillBalance Set HName = '终极照明术' where Type =218;
Update SkillBalance Set HName = '活跃攻击' where Type =219;
Update SkillBalance Set HName = '回避术' where Type =220;
Update SkillBalance Set HName = '旋风烈斩' where Type =221;
Update SkillBalance Set HName = '精确打击' where Type =222;
Update SkillBalance Set HName = '背刺' where Type =223;
Update SkillBalance Set HName = '防御崩坏' where Type =224;
Update SkillBalance Set HName = '伽玛斩' where Type =225;
Update SkillBalance Set HName = '十字护卫' where Type =226;
Update SkillBalance Set HName = '火之灵石' where Type =227;
Update SkillBalance Set HName = '冰之灵石' where Type =228;
Update SkillBalance Set HName = '沙之灵石' where Type =229;
Update SkillBalance Set HName = '眩晕' where Type =230;
Update SkillBalance Set HName = '卡萨之箭' where Type =231;
Update SkillBalance Set HName = '火焰之触' where Type =232;
Update SkillBalance Set HName = '地狱火海' where Type =233;
Update SkillBalance Set HName = '光耀之环' where Type =234;
Update SkillBalance Set HName = '烈焰之矢' where Type =235;
Update SkillBalance Set HName = '冰之领域' where Type =236;
Update SkillBalance Set HName = '水之壁障' where Type =237;
Update SkillBalance Set HName = '水神之触' where Type =238;
Update SkillBalance Set HName = '治愈女神' where Type =239;
Update SkillBalance Set HName = '诅咒净化' where Type =240;
Update SkillBalance Set HName = '藤蔓' where Type =241;
Update SkillBalance Set HName = '真实视野' where Type =242;
Update SkillBalance Set HName = '石钻冲击' where Type =243;
Update SkillBalance Set HName = '净化之息' where Type =244;
Update SkillBalance Set HName = '大地之牙' where Type =245;
Update SkillBalance Set HName = '灵魂吸收' where Type =246;
Update SkillBalance Set HName = '召唤-精灵' where Type =247;
Update SkillBalance Set HName = '灵魂漂流' where Type =248;
Update SkillBalance Set HName = '魔法爆击' where Type =249;
Update SkillBalance Set HName = '液体喷发' where Type =250;
Update SkillBalance Set HName = '致命打击' where Type =251;
Update SkillBalance Set HName = '神之精灵' where Type =252;
Update SkillBalance Set HName = '灭日修罗斩' where Type =253;
Update SkillBalance Set HName = '火焰之步' where Type =254;
Update SkillBalance Set HName = '放血术' where Type =255;
Update SkillBalance Set HName = '强力治愈术' where Type =256;
Update SkillBalance Set HName = '神之阻咒' where Type =257;
Update SkillBalance Set HName = '血腥巅峰' where Type =258;
Update SkillBalance Set HName = '激发' where Type =259;
Update SkillBalance Set HName = '烈炎剑' where Type =260;
Update SkillBalance Set HName = '快速恢复' where Type =261;
Update SkillBalance Set HName = '枪械熟练度 1' where Type =262;
Update SkillBalance Set HName = '大容量填装' where Type =263;
Update SkillBalance Set HName = '爆裂射击' where Type =264;
Update SkillBalance Set HName = '枪械熟练度 2' where Type =265;
Update SkillBalance Set HName = '摩尔散射' where Type =266;
Update SkillBalance Set HName = '转生术' where Type =267;
Update SkillBalance Set HName = '血盾' where Type =268;
Update SkillBalance Set HName = '放置陷阱' where Type =269;
Update SkillBalance Set HName = '圣水制造' where Type =270;
Update SkillBalance Set HName = '仁慈大地' where Type =271;
Update SkillBalance Set HName = '神圣装甲' where Type =272;
Update SkillBalance Set HName = '变身-狼人' where Type =273;
Update SkillBalance Set HName = '石之肌肤' where Type =274;
Update SkillBalance Set HName = '酸性喷发' where Type =275;
Update SkillBalance Set HName = '吸血神鸦' where Type =276;
Update SkillBalance Set HName = '黑暗神力' where Type =277;
Update SkillBalance Set HName = '死亡之吻' where Type =278;
Update SkillBalance Set HName = 'Not Defined' where Type =279;
Update SkillBalance Set HName = '瞬间移动' where Type =280;
Update SkillBalance Set HName = '烈焰指' where Type =281;
Update SkillBalance Set HName = '召唤-火元素' where Type =282;
Update SkillBalance Set HName = '赤雨流焰' where Type =283;
Update SkillBalance Set HName = '地狱火' where Type =284;
Update SkillBalance Set HName = '疾风冰矛' where Type =285;
Update SkillBalance Set HName = '寒冰护甲' where Type =286;
Update SkillBalance Set HName = '召唤-水元素' where Type =287;
Update SkillBalance Set HName = '制约喷泉' where Type =288;
Update SkillBalance Set HName = '复活' where Type =289;
Update SkillBalance Set HName = '复活强化' where Type =290;
Update SkillBalance Set HName = '大地护甲' where Type =291;
Update SkillBalance Set HName = '大地祝福' where Type =292;
Update SkillBalance Set HName = '神耀印记' where Type =293;
Update SkillBalance Set HName = '流星雨' where Type =294;
Update SkillBalance Set HName = '锐利之轮' where Type =295;
Update SkillBalance Set HName = '回旋斩' where Type =296;
Update SkillBalance Set HName = '水之祈祷' where Type =297;
Update SkillBalance Set HName = '致命爆发' where Type =298;
Update SkillBalance Set HName = '火之祈祷' where Type =299;
Update SkillBalance Set HName = '致残之蛇' where Type =300;
Update SkillBalance Set HName = '沙之祈祷' where Type =301;
Update SkillBalance Set HName = '光速冲击' where Type =302;
Update SkillBalance Set HName = '精灵之怒' where Type =303;
Update SkillBalance Set HName = '雷神斩' where Type =304;
Update SkillBalance Set HName = '奇迹之魂' where Type =305;
Update SkillBalance Set HName = '钢铁意志' where Type =306;
Update SkillBalance Set HName = '狂野冰原' where Type =307;
Update SkillBalance Set HName = '冰河1' where Type =308;
Update SkillBalance Set HName = '冰河2' where Type =309;
Update SkillBalance Set HName = '冰钻' where Type =310;
Update SkillBalance Set HName = '冰雹' where Type =311;
Update SkillBalance Set HName = '大冰雹' where Type =312;
Update SkillBalance Set HName = '冰冻波涛' where Type =313;
Update SkillBalance Set HName = '地雷爆炸' where Type =314;
Update SkillBalance Set HName = '破片雷爆炸' where Type =315;
Update SkillBalance Set HName = '愉悦引爆' where Type =316;
Update SkillBalance Set HName = 'Deleo Efficio' where Type =317;
Update SkillBalance Set HName = 'Reputo Factum' where Type =318;
Update SkillBalance Set HName = '雷神之剑' where Type =319;
Update SkillBalance Set HName = '燃烧之魂' where Type =320;
Update SkillBalance Set HName = '发射燃烧之魂' where Type =321;
Update SkillBalance Set HName = '安装炮塔' where Type =322;
Update SkillBalance Set HName = '炮塔火力' where Type =323;
Update SkillBalance Set HName = '幻灭之钳' where Type =324;
Update SkillBalance Set HName = '幻灭之钳2' where Type =325;
Update SkillBalance Set HName = '幻灭之钳3' where Type =326;
Update SkillBalance Set HName = '太阳风' where Type =327;
Update SkillBalance Set HName = '暴力幻影' where Type =328;
Update SkillBalance Set HName = '招唤-血腥脉管' where Type =329;
Update SkillBalance Set HName = '血腥脉管之火' where Type =330;
Update SkillBalance Set HName = '致命爆发熟练度' where Type =331;
Update SkillBalance Set HName = '致残之蛇熟练度' where Type =332;
Update SkillBalance Set HName = '赤雨流焰熟练度' where Type =333;
Update SkillBalance Set HName = '疾风冰矛熟练度' where Type =334;
Update SkillBalance Set HName = '大地护甲熟练度' where Type =335;
Update SkillBalance Set HName = '飞斧' where Type =336;
Update SkillBalance Set HName = '霸气火棍' where Type =337;
Update SkillBalance Set HName = '飞斧链' where Type =338;
Update SkillBalance Set HName = '多重飞斧' where Type =339;
Update SkillBalance Set HName = '操纵火焰' where Type =340;
Update SkillBalance Set HName = '无限闪电' where Type =341;
Update SkillBalance Set HName = '喷流' where Type =342;
Update SkillBalance Set HName = '离子火箭发射器' where Type =343;
Update SkillBalance Set HName = '亲密圣杯' where Type =344;
Update SkillBalance Set HName = '爆破之星' where Type =345;
Update SkillBalance Set HName = '点燃' where Type =346;
Update SkillBalance Set HName = '缚魂术' where Type =347;
Update SkillBalance Set HName = '尖锐冰雹' where Type =348;
Update SkillBalance Set HName = '招唤-Miga' where Type =349;
Update SkillBalance Set HName = '招唤-Miga攻击' where Type =350;
Update SkillBalance Set HName = '冰冻地平线' where Type =351;
Update SkillBalance Set HName = '大地之怒' where Type =352;
Update SkillBalance Set HName = '狂轰滥炸' where Type =353;
Update SkillBalance Set HName = '自毁' where Type =354;
Update SkillBalance Set HName = 'AR攻击' where Type =355;
Update SkillBalance Set HName = 'SMG攻击' where Type =356;
Update SkillBalance Set HName = '手雷攻击' where Type =357;
Update SkillBalance Set HName = '巨龙卷风' where Type =358;
Update SkillBalance Set HName = '飞车一击' where Type =359;
Update SkillBalance Set HName = '鱼叉炸弹' where Type =360;
Update SkillBalance Set HName = '传递治疗' where Type =361;
Update SkillBalance Set HName = '烂苹果' where Type =362;
Update SkillBalance Set HName = '野狼' where Type =363;
Update SkillBalance Set HName = '心态失常' where Type =364;
Update SkillBalance Set HName = '光晕' where Type =365;
Update SkillBalance Set HName = '命运' where Type =366;
Update SkillBalance Set HName = '烈火' where Type =367;
Update SkillBalance Set HName = '风暴之影' where Type =368;
Update SkillBalance Set HName = 'Not Defined' where Type =369;
Update SkillBalance Set HName = 'Not Defined' where Type =370;
Update SkillBalance Set HName = 'Not Defined' where Type =371;
Update SkillBalance Set HName = 'Not Defined' where Type =372;
Update SkillBalance Set HName = 'Not Defined' where Type =373;
Update SkillBalance Set HName = 'Not Defined' where Type =374;
Update SkillBalance Set HName = '秋府倪磐 何福扁' where Type =375;
Update SkillBalance Set HName = 'Bomb-Splinter' where Type =376;
Update SkillBalance Set HName = 'Bomb-Acer' where Type =377;
Update SkillBalance Set HName = 'Bomb-Bulls' where Type =378;
Update SkillBalance Set HName = 'Bomb-Stun' where Type =379;
Update SkillBalance Set HName = 'Bomb-Crossbow' where Type =380;
Update SkillBalance Set HName = 'Bomb-Twister' where Type =381;
Update SkillBalance Set HName = 'Mine-AnkleKiller' where Type =382;
Update SkillBalance Set HName = 'Mine-Pomz' where Type =383;
Update SkillBalance Set HName = 'Mine-AP-C1' where Type =384;
Update SkillBalance Set HName = 'Mine-DiamondBack' where Type =385;
Update SkillBalance Set HName = 'Mine-Swift-EX' where Type =386;
Update SkillBalance Set HName = 'Mine-SideWinder' where Type =387;
Update SkillBalance Set HName = 'Mine-Cobra' where Type =388;
Update SkillBalance Set HName = 'Not Defined' where Type =389;
Update SkillBalance Set HName = 'Not Defined' where Type =390;
Update SkillBalance Set HName = 'Not Defined' where Type =391;
Update SkillBalance Set HName = 'Not Defined' where Type =392;
Update SkillBalance Set HName = 'Not Defined' where Type =393;
Update SkillBalance Set HName = 'Not Defined' where Type =394;
Update SkillBalance Set HName = 'Not Defined' where Type =395;
Update SkillBalance Set HName = 'Not Defined' where Type =396;
Update SkillBalance Set HName = 'Not Defined' where Type =397;
Update SkillBalance Set HName = 'Not Defined' where Type =398;
Update SkillBalance Set HName = 'Not Defined' where Type =399;
Update SkillBalance Set HName = 'Not Defined' where Type =400;
Update SkillBalance Set HName = 'Not Defined' where Type =401;
Update SkillBalance Set HName = 'Not Defined' where Type =402;
Update SkillBalance Set HName = '犬己扁' where Type =403;
Update SkillBalance Set HName = 'Not Defined' where Type =404;
Update SkillBalance Set HName = 'Not Defined' where Type =405;
Update SkillBalance Set HName = '孤飘' where Type =406;
Update SkillBalance Set HName = 'Not Defined' where Type =407;
Update SkillBalance Set HName = '菩剐府 焊呈胶' where Type =408;
Update SkillBalance Set HName = 'Not Defined' where Type =409;
Update SkillBalance Set HName = 'Not Defined' where Type =410;
Update SkillBalance Set HName = 'Not Defined' where Type =411;
Update SkillBalance Set HName = 'Not Defined' where Type =412;
Update SkillBalance Set HName = 'Not Defined' where Type =413;
Update SkillBalance Set HName = 'Not Defined' where Type =414;
Update SkillBalance Set HName = 'Not Defined' where Type =415;
Update SkillBalance Set HName = 'Not Defined' where Type =416;
Update SkillBalance Set HName = 'Not Defined' where Type =417;
Update SkillBalance Set HName = 'Not Defined' where Type =418;
Update SkillBalance Set HName = 'Not Defined' where Type =419;
Update SkillBalance Set HName = 'Not Defined' where Type =420;
Update SkillBalance Set HName = 'Not Defined' where Type =421;
Update SkillBalance Set HName = 'Not Defined' where Type =422;
Update SkillBalance Set HName = 'Not Defined' where Type =423;
Update SkillBalance Set HName = 'Not Defined' where Type =424;
Update SkillBalance Set HName = 'Not Defined' where Type =425;
Update SkillBalance Set HName = 'Not Defined' where Type =426;
Update SkillBalance Set HName = 'Not Defined' where Type =427;
Update SkillBalance Set HName = 'Not Defined' where Type =428;
Update SkillBalance Set HName = 'Not Defined' where Type =429;
Update SkillBalance Set HName = 'Not Defined' where Type =430;
Update SkillBalance Set HName = 'Not Defined' where Type =431;
Update SkillBalance Set HName = 'Not Defined' where Type =432;
Update SkillBalance Set HName = 'Not Defined' where Type =433;
Update SkillBalance Set HName = 'Not Defined' where Type =434;
Update SkillBalance Set HName = 'Not Defined' where Type =435;
Update SkillBalance Set HName = 'Not Defined' where Type =436;
Update SkillBalance Set HName = 'Not Defined' where Type =437;
Update SkillBalance Set HName = 'Not Defined' where Type =438;
Update SkillBalance Set HName = 'Not Defined' where Type =439;
Update SkillBalance Set HName = 'Not Defined' where Type =440;
Update SkillBalance Set HName = 'Not Defined' where Type =441;
Update SkillBalance Set HName = '乔狼 己辑 酒福皋啊' where Type =442;
Update SkillBalance Set HName = '乔狼 己辑 固龋饭' where Type =443;
Update SkillBalance Set HName = '乔狼 己辑 虐肺' where Type =444;
Update SkillBalance Set HName = '乔狼 己辑 酒捞聪' where Type =445;
Update SkillBalance Set HName = '乔狼 己辑 弊饭绊府' where Type =446;
Update SkillBalance Set HName = '乔狼 己辑 能磨府酒' where Type =447;
Update SkillBalance Set HName = '乔狼 己辑 饭瘤坷胶' where Type =448;
Update SkillBalance Set HName = '乔狼 己辑 鳃副' where Type =449;
Update SkillBalance Set HName = '乔狼 己辑 鲤宏' where Type =450;
Update SkillBalance Set HName = '乔狼 己辑 匙付' where Type =451;
Update SkillBalance Set HName = '乔狼 己辑 酒肺荤' where Type =452;
Update SkillBalance Set HName = '乔狼 己辑 瞒胶颇' where Type =453;
Update SkillBalance Set HName = '矾宏眉牢' where Type =454;
Update SkillBalance Set HName = 'Not Defined' where Type =455;
Update SkillBalance Set HName = '锅开扁' where Type =456;
Update SkillBalance Set HName = '胶困欺 焊呈胶 1' where Type =457;
Update SkillBalance Set HName = '胶困欺 焊呈胶 2' where Type =458;
Update SkillBalance Set HName = '胶困欺 焊呈胶 3' where Type =459;
Update SkillBalance Set HName = '胶困欺 焊呈胶 4' where Type =460;
Update SkillBalance Set HName = '胶困欺 焊呈胶 5' where Type =461;
Update SkillBalance Set HName = '胶困欺 焊呈胶 6' where Type =462;
Update SkillBalance Set HName = '胶困欺 焊呈胶 7' where Type =463;
Update SkillBalance Set HName = '胶困欺 焊呈胶 8' where Type =464;
Update SkillBalance Set HName = '胶困欺 焊呈胶 9' where Type =465;
Update SkillBalance Set HName = '胶困欺 焊呈胶 10' where Type =466;
Update SkillBalance Set HName = '胶困欺 焊呈胶 11' where Type =467;
Update SkillBalance Set HName = '胶困欺 焊呈胶 12' where Type =468;
Update SkillBalance Set HName = '龙靛饭 饭绢 涝厘 啊瓷' where Type =469;
Update SkillBalance Set HName = '喉扼牢靛聪胶' where Type =470;
Update SkillBalance Set HName = 'Not Defined' where Type =471;
Update SkillBalance Set HName = '版氰摹 焊呈胶' where Type =472;
