
enum VAMPIRE_PART{
	PART_COAT1,
	PART_COAT2,
	PART_COAT3,

	VAMPIRE_PART_MAX,
};

enum ADVANCEMENT_CLASS_VAMPIRE_PART {
	AC_PART_COAT,
	AC_PART_WEAPON,

	AC_PART_MAX
};

enum OUSTERS_PART {
	PART_SHAKRAM,
	COAT1,
	COAT2,
	COAT3,
	COAT4,

	OUSTERS_PART_MAX,
};

enum {
	OUSTERS_ACTION_SHAK_STOP = 0,
	OUSTERS_ACTION_SHAK_MOVE,
	OUSTERS_ACTION_SHAK_ATTACK,
	OUSTERS_ACTION_SKILL,
	OUSTERS_ACTION_DAMAGED,
	OUSTERS_ACTION_DRAINED,
	OUSTERS_ACTION_DIE,
	
	OUSTERS_ACTION_STOP,
	OUSTERS_ACTION_MOVE,
	OUSTERS_ACTION_SHAK_SKILL,	
	OUSTERS_ACTION_MAGIC_ATTACK,
	OUSTERS_ACTION_GETTING_SOUL,
	OUSTERS_ACTION_FAST_MOVE_STOP,
	OUSTERS_ACTION_FAST_MOVE,
	OUSTERS_ACTION_SHAK_ATTACK_SLOW,
	OUSTERS_ACTION_SHAK_ATTACK_FAST,
	OUSTERS_ACTION_SHAK_SKILL_SLOW,
	OUSTERS_ACTION_SHAK_SKILL_FAST,

	OUSTERS_ACTION_MAX,
};


enum SLAYER_PART {
	PART_HELMET1,
	PART_UPPER_CLOTHES1,
	PART_LOWER_CLOTHES1,
	PART_SMG,		
	PART_BLADE,		// 도
	PART_SHIELD1,
	PART_SHIELD2,
	PART_SHIELD3,
	PART_SG,	
	PART_SWORD,		// 검
	PART_AR,				
	PART_HEAD1,
	PART_HEAD2,
	PART_HEAD3,	
	PART_HELMET2,	
	PART_UPPER_CLOTHES2,
	PART_LOWER_CLOTHES2,
	PART_CROSS,
	PART_SR,
	PART_BIKE1,
	PART_UPPER_CLOTHES0,
	PART_LOWER_CLOTHES0,
#ifdef _TEMP_FOR_INTERFACE	
	PART_HAIR1,	// 임시
	PART_HAIR2,
	PART_HAIR3,
#endif
	SLAYER_PART_MAX,
};

enum
{
	ACTION_ADVANCEMENT_STOP = 0,
	ACTION_ADVANCEMENT_MOVE,
	ACTION_ADVANCEMENT_DAMAGED,
	ACTION_ADVANCEMENT_DIE,
	ACTION_ADVANCEMENT_DRAIN,
	ACTION_ADVANCEMENT_DRAINED,

	ACTION_ADVANCEMENT_ATTACK_SLOW,
	ACTION_ADVANCEMENT_ATTACK_NORMAL,
	ACTION_ADVANCEMENT_ATTACK_FAST,

	ACTION_ADVANCEMENT_SKILL_SLOW,
	ACTION_ADVANCEMENT_SKILL_NORMAL,
	ACTION_ADVANCEMENT_SKILL_FAST,

	ACTION_ADVANCEMENT_MAGIC,
	ACTION_ADVANCEMENT_MAGIC_ATTACK,
	ACTION_ADVANCEMENT_SPECIAL,
	ACTION_ADVANCEMENT_CREATE_WEAPON,
	ACTION_ADVANCEMENT_DESTROY_WEAPON,
	
	ACTION_ADVANCEMENT_MAX,
};

// !주의! 액션이 변경되면 아래의 define도 변경되야 한다.
enum {
	ACTION_STOP	 = 	0,
	ACTION_MOVE,
	ACTION_ATTACK,	
	ACTION_SKILL,			// magic
	ACTION_DAMAGED,	
	ACTION_DRAINED,	
	ACTION_DIE,		
	ACTION_DRAIN,			// 

	ACTION_SR,
	ACTION_AR,
	ACTION_SWORD,
	ACTION_BLADE,
	ACTION_THROW1,
	ACTION_BIKE_MOVE1,
	ACTION_SG,
	ACTION_SMG,
	ACTION_SWORD2,
	ACTION_BLADE2,
	ACTION_THROW2,
	ACTION_BIKE_STOP1,
	
	ACTION_SR_SLOW,
	ACTION_SR_FAST,
	ACTION_AR_SLOW,
	ACTION_AR_FAST,
	ACTION_SG_SLOW,
	ACTION_SG_FAST,
	ACTION_SMG_SLOW,
	ACTION_SMG_FAST,

	ACTION_SWORD_SLOW,
	ACTION_SWORD_FAST,
	ACTION_BLADE_SLOW,
	ACTION_BLADE_FAST,
	ACTION_SWORD2_SLOW,
	ACTION_SWORD2_FAST,
	ACTION_BLADE2_SLOW,
	ACTION_BLADE2_FAST,
	ACTION_MAX,		
};

enum PROMOTION_SLAYER_PART
{
	PS_BODY = 0,
	PS_HELMET,
	PS_SWORD,
	PS_BLADE,
	PS_CROSS,
	PS_MACE,
	PS_GUN_AR,
	PS_GUN_SR,
	PS_SHIELD,
	PS_BIKE_1,
	PS_BIKE_2,
	PS_SHOULDER,

	PS_PART_MAX,
};

enum {
	ACTION_SLAYER_PROMOTION_STOP_SWORD = 0,
	ACTION_SLAYER_PROMOTION_STOP_BLADE,
	ACTION_SLAYER_PROMOTION_STOP_GUN,
	ACTION_SLAYER_PROMOTION_STOP_MACE_AND_CROSS,
	
	ACTION_SLAYER_PROMOTION_MOVE_SWORD,
	ACTION_SLAYER_PROMOTION_MOVE_BLADE,
	ACTION_SLAYER_PROMOTION_MOVE_GUN,
	ACTION_SLAYER_PROMOTION_MOVE_MACE_AND_CROSS,

	ACTION_SLAYER_PROMOTION_ATTACK_SWORD_SLOW,
	ACTION_SLAYER_PROMOTION_ATTACK_SWORD_NORMAL,
	ACTION_SLAYER_PROMOTION_ATTACK_SWORD_FAST,
	
	ACTION_SLAYER_PROMOTION_ATTACK_BLADE_SLOW,
	ACTION_SLAYER_PROMOTION_ATTACK_BLADE_NORMAL,
	ACTION_SLAYER_PROMOTION_ATTACK_BLADE_FAST,
	
	ACTION_SLAYER_PROMOTION_ATTACK_GUN_AR_SLOW,
	ACTION_SLAYER_PROMOTION_ATTACK_GUN_AR_NORMAL,
	ACTION_SLAYER_PROMOTION_ATTACK_GUN_AR_FAST,

	ACTION_SLAYER_PROMOTION_ATTACK_GUN_SR_SLOW,
	ACTION_SLAYER_PROMOTION_ATTACK_GUN_SR_NORMAL,
	ACTION_SLAYER_PROMOTION_ATTACK_GUN_SR_FAST,


	ACTION_SLAYER_PROMOTION_SKILL_SWORD_SLOW,
	ACTION_SLAYER_PROMOTION_SKILL_SWORD_NORMAL,
	ACTION_SLAYER_PROMOTION_SKILL_SWORD_FAST,

	ACTION_SLAYER_PROMOTION_SKILL_BLADE_SLOW,
	ACTION_SLAYER_PROMOTION_SKILL_BLADE_NORMAL,
	ACTION_SLAYER_PROMOTION_SKILL_BLADE_FAST,

	ACTION_SLAYER_PROMOTION_SKILL_GUN_SLOW,
	ACTION_SLAYER_PROMOTION_SKILL_GUN_NORMAL,
	ACTION_SLAYER_PROMOTION_SKILL_GUN_FAST,
	
	ACTION_SLAYER_PROMOTION_MAGIC,
	ACTION_SLAYER_PROMOTION_MAGIC_ATTACK,

	ACTION_SLAYER_PROMOTION_DRAINED,
	ACTION_SLAYER_PROMOTION_DAMAGED_SWORD,
	ACTION_SLAYER_PROMOTION_DAMAGED_BLADE,
	ACTION_SLAYER_PROMOTION_DAMAGED_GUN,
	ACTION_SLAYER_PROMOTION_DAMAGED_CROSS_MACE,
	ACTION_SLAYER_PROMOTION_DIE,

	ACTION_SLAYER_PROMOTION_BIKE_MOVE,
	ACTION_SLAYER_PROMOTION_BIKE_STOP,

	ACTION_SLAYER_PROMOTION_SPECIAL,
	ACTION_SLAYER_PROMOTION_SPECIAL_2,
	ACTION_SLAYER_PROMOTION_SLIDING,
	ACTION_SLAYER_PROMOTION_SLIDING_END,

	ACTION_SLAYER_PROMOTION_MAX,
};

enum
{
	ACTION_OUSTERS_PROMOTION_CHAKRAM_STOP = 0,
	ACTION_OUSTERS_PROMOTION_CHAKRAM_MOVE,
	ACTION_OUSTERS_PROMOTION_WRISTLET_STOP,
	ACTION_OUSTERS_PROMOTION_WRISTLET_MOVE,

	ACTION_OUSTERS_PROMOTION_ATTACK_SLOW,
	ACTION_OUSTERS_PROMOTION_ATTACK_NORMAL,
	ACTION_OUSTERS_PROMOTION_ATTACK_FAST,
	ACTION_OUSTERS_PROMOTION_SKILL_SLOW,
	ACTION_OUSTERS_PROMOTION_SKILL_NORMAL,
	ACTION_OUSTERS_PROMOTION_SKILL_FAST,

	ACTION_OUSTERS_PROMOTION_MAGIC_ATTACK,

	ACTION_OUSTERS_PROMOTION_MAGIC,
	ACTION_OUSTERS_PROMOTION_ABSORB_SOUL,
	ACTION_OUSTERS_PROMOTION_DRAINED,
	ACTION_OUSTERS_PROMOTION_DIE,
	ACTION_OUSTERS_PROMOTION_DAMAGED,
	ACTION_OUSTERS_PROMOTION_SPECIAL,

	ACTION_OUSTERS_PROMOTION_FAST_MOVE_STOP,
	ACTION_OUSTERS_PROMOTION_FAST_MOVE,

	ACTION_OUSTERS_PROMOTION_MAX
};

enum PROMOTION_OUSTERS_PART {
	PO_PART_SHAKRAM,
	PO_COAT1,
	
	PO_PART_MAX,
};


/*
enum SLAYER_PROMOTION_PART {
	PART_HELMET1,
	PART_UPPER_CLOTHES1,
	PART_LOWER_CLOTHES1,
	PART_SMG,		
	PART_BLADE,		// 도
	PART_SHIELD1,
	PART_SHIELD2,
	PART_SHIELD3,
	PART_SG,	
	PART_SWORD,		// 검
	PART_AR,				
	PART_HEAD1,
	PART_HEAD2,
	PART_HEAD3,	
	PART_HELMET2,	
	PART_UPPER_CLOTHES2,
	PART_LOWER_CLOTHES2,
	PART_CROSS,
	PART_SR,
	PART_BIKE1,
	PART_UPPER_CLOTHES0,
	PART_LOWER_CLOTHES0,
#ifdef _TEMP_FOR_INTERFACE	
	PART_HAIR1,	// 임시
	PART_HAIR2,
	PART_HAIR3,
#endif
	SLAYER_PART_MAX,
};
*/