//////////////////////////////////////////////////////////////////////////////
/// \file PromotionSlayerActionName.h
/// \author sonee
/// \date 2004.12.9
//////////////////////////////////////////////////////////////////////////////

#pragma once


const char* strPromotionSlayerAction[ ACTION_SLAYER_PROMOTION_MAX ] =
{
	"검정지",
	"도정지",
	"총정지",
	"십자가정지",	
	
	"검걷기",
	"도걷기",
	"총걷기",
	"십자가걷기",

	"검공격SLOW",
	"검공격NORMAL",
	"검공격FAST",
	
	"도공격SLOW",
	"도공격NORMAL",
	"도공격FAST",
	
	"AR공격SLOW",
	"AR공격NORMAL",
	"AR공격FAST",

	"SR공격SLOW",
	"SR공격NORMAL",
	"SR공격FAST",

	"검스킬SLOW",
	"검스킬NORMAL",
	"검스킬FAST",

	"도스킬SLOW",
	"도스킬NORMAL",
	"도스킬FAST",

	"총스킬SLOW",
	"총스킬NORMAL",
	"총스킬FAST",
	
	"마법시전",
	"마법공격",
	
	"흡혈당하기",
	"검맞기",
	"도맞기",
	"총맞기",
	"십자가메이스맞기",
	"죽기",

	"오토바이이동",
	"오토바이정지",

	"특수검도",
	"특수총십자가",
	"슬라이딩진행",
	"슬라이딩끝"
};

const char* strPromotionSlayerActionForSearch[ ACTION_SLAYER_PROMOTION_MAX ] =
{
	"검정지",
	"도정지",
	"총정지",
	"십자가정지",	
	
	"검걷기",
	"도걷기",
	"총걷기",
	"십자가걷기",

	"검스킬",
	"검스킬",
	"검스킬",
	
	"도공격",
	"도공격",
	"도공격",
	
	"총공격",
	"총공격",
	"총공격",

	"총공격",
	"총공격",
	"총공격",

	"검스킬",
	"검스킬",
	"검스킬",

	"도스킬",
	"도스킬",
	"도스킬",

	"총스킬",
	"총스킬",
	"총스킬",
	
	"마법시전",
	"마법공격",
	
	"흡혈당하기",
	"검맞기",
	"도맞기",
	"총맞기",
	"십자가메이스맞기",
	"죽기",

	"오토바이이동",
	"오토바이정지",

	"특수검도",
	"특수총십자가",
	"슬라이딩진행",
	"슬라이딩끝"
};

const DWORD g_PromotionSlayerActionIndex[ ACTION_SLAYER_PROMOTION_MAX ] =
{
	ACTION_SLAYER_PROMOTION_STOP_SWORD,
	ACTION_SLAYER_PROMOTION_STOP_BLADE,
	ACTION_SLAYER_PROMOTION_STOP_GUN,
	ACTION_SLAYER_PROMOTION_STOP_MACE_AND_CROSS,
	
	ACTION_SLAYER_PROMOTION_MOVE_SWORD,
	ACTION_SLAYER_PROMOTION_MOVE_BLADE,
	ACTION_SLAYER_PROMOTION_MOVE_GUN,
	ACTION_SLAYER_PROMOTION_MOVE_MACE_AND_CROSS,

	ACTION_SLAYER_PROMOTION_ATTACK_SWORD_SLOW,
	ACTION_SLAYER_PROMOTION_ATTACK_SWORD_NORMAL,
	ACTION_SLAYER_PROMOTION_ATTACK_SWORD_FAST,
	
	ACTION_SLAYER_PROMOTION_ATTACK_BLADE_SLOW,
	ACTION_SLAYER_PROMOTION_ATTACK_BLADE_NORMAL,
	ACTION_SLAYER_PROMOTION_ATTACK_BLADE_FAST,
	
	ACTION_SLAYER_PROMOTION_ATTACK_GUN_AR_SLOW,
	ACTION_SLAYER_PROMOTION_ATTACK_GUN_AR_NORMAL,
	ACTION_SLAYER_PROMOTION_ATTACK_GUN_AR_FAST,

	ACTION_SLAYER_PROMOTION_ATTACK_GUN_SR_SLOW,
	ACTION_SLAYER_PROMOTION_ATTACK_GUN_SR_NORMAL,
	ACTION_SLAYER_PROMOTION_ATTACK_GUN_SR_FAST,

	ACTION_SLAYER_PROMOTION_SKILL_SWORD_SLOW,
	ACTION_SLAYER_PROMOTION_SKILL_SWORD_NORMAL,
	ACTION_SLAYER_PROMOTION_SKILL_SWORD_FAST,

	ACTION_SLAYER_PROMOTION_SKILL_BLADE_SLOW,
	ACTION_SLAYER_PROMOTION_SKILL_BLADE_NORMAL,
	ACTION_SLAYER_PROMOTION_SKILL_BLADE_FAST,

	ACTION_SLAYER_PROMOTION_SKILL_GUN_SLOW,
	ACTION_SLAYER_PROMOTION_SKILL_GUN_NORMAL,
	ACTION_SLAYER_PROMOTION_SKILL_GUN_FAST,
	
	ACTION_SLAYER_PROMOTION_MAGIC,
	ACTION_SLAYER_PROMOTION_MAGIC_ATTACK,

	ACTION_SLAYER_PROMOTION_DRAINED,
	ACTION_SLAYER_PROMOTION_DAMAGED_SWORD,
	ACTION_SLAYER_PROMOTION_DAMAGED_BLADE,
	ACTION_SLAYER_PROMOTION_DAMAGED_GUN,
	ACTION_SLAYER_PROMOTION_DAMAGED_CROSS_MACE,
	ACTION_SLAYER_PROMOTION_DIE,

	ACTION_SLAYER_PROMOTION_BIKE_MOVE,
	ACTION_SLAYER_PROMOTION_BIKE_STOP,

	ACTION_SLAYER_PROMOTION_SPECIAL,
	ACTION_SLAYER_PROMOTION_SPECIAL_2,
	ACTION_SLAYER_PROMOTION_SLIDING,
	ACTION_SLAYER_PROMOTION_SLIDING_END,
};

const char* strPromotionSlayerPart[ PS_PART_MAX ] =
{
	"몸",
	"헬멧",
	"검",
	"도",
	"십자가",
	"메이스",
	"AR",
	"SR",
	"방패",
	"오토바이1",
	"오토바이2",
	"어깨견장"
};

const BYTE ACSlayerPartType[ PS_PART_MAX ] =
{
	ADDON_AC_BODY,
	ADDON_AC_HELMET,
	ADDON_AC_RIGHTHAND,
	ADDON_AC_RIGHTHAND,
	ADDON_AC_RIGHTHAND,
	ADDON_AC_RIGHTHAND,
	ADDON_AC_RIGHTHAND,
	ADDON_AC_RIGHTHAND,
	ADDON_AC_LEFTHAND,
	ADDON_AC_MOTOR,
	ADDON_AC_MOTOR,
	ADDON_AC_SHOULDER,
};